### ISSUE TITLE
Is it possible to setup multiple tasks per day and also without sleeping in between?

### ISSUE THREAD

**Issue by namork** [SensorsIot/ESPDailyTaskNTP#4]
maybe i'm wrong here. but could i use the library as a scheduler for several task and just once a day synchronize the clock? as for now the esp2866 wouldn't have to sleep in between. thanks for any hint.

**Comment by SensorsIot** [comment]
If your ESP does not have to sleep you can poll the NTP server in the loop and decide what to do.
